modalities:
  [
    { acc1: [5, 6, 7], gyro1: [8, 9, 10], mag1: [11, 12, 13] },
    { acc1: [5, 6, 7], gyro1: [8, 9, 10], mag1: [11, 12, 13] },
    { acc2: [14, 15, 16], gyro2: [17, 18, 19], mag2: [20, 21, 22] },
    { acc2: [14, 15, 16], gyro2: [17, 18, 19], mag2: [20, 21, 22] },
    {acc1: [5, 6, 7], gyro1: [8, 9, 10], mag1: [11, 12, 13],acc2: [14, 15, 16], gyro2: [17, 18, 19], mag2: [20, 21, 22]
    }
  ]

n_clients: 5
n_sets_train: 5
n_sets_test: 1
batch_size: 128
fedGlob: True
fedLoc: True
lr: 1e-4
optim: Adam
lg_frac: 0
rounds: 2000
epochs: 8
iid: False
penalty: True
classes_per_client_training: 8
classes_per_client_testing: 12
train_data_portion: 1
test_data_portion: 0
hidden_dims: 2
mlp_dims: [32, 16, 12]
data_path: ["/home/preslav/Projects/fedavg-par/data/data_2_std.csv",
          "/home/preslav/Projects/fedavg-par/data/data_3_std.csv",
          "/home/preslav/Projects/fedavg-par/data/data_4_std.csv",
          "/home/preslav/Projects/fedavg-par/data/data_5_std.csv",
          "/home/preslav/Projects/fedavg-par/data/data_6_std.csv",
          "/home/preslav/Projects/fedavg-par/data/data_7_std.csv",
          "/home/preslav/Projects/fedavg-par/data/data_8_std.csv"]
train_path: "/home/preslav/Projects/fedavg-par/data/data_1_std.csv"

train: 3
eval: False
corr: [
     [0,1,2,3,4]
]
sig: False
diff: False